# Generated by Django 4.2 on 2023-07-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senderemail',
            old_name='is_checked',
            new_name='is_checked_pass',
        ),
    ]
