# Generated by Django 4.2 on 2023-07-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_rename_is_checked_senderemail_is_checked_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senderemail',
            old_name='is_checked_pass',
            new_name='is_check_pass',
        ),
    ]
