# Generated by Django 4.2 on 2023-05-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_usersenders_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientcontact',
            name='comment',
            field=models.TextField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='recipientcontact',
            name='senders',
            field=models.ManyToManyField(blank=True, default=[], to='sender.usersenders'),
        ),
    ]
