# Generated by Django 4.2 on 2023-07-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_rename_is_checked_pass_senderemail_is_check_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderemail',
            name='is_check_pass',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
