# Generated by Django 4.2 on 2023-07-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_alter_recipientcontact_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientcontact',
            name='is_phone_whatsapp_reg',
            field=models.BooleanField(default=False, verbose_name='Телефон проверен на наличие в WhatsApp'),
        ),
        migrations.AddField(
            model_name='recipientcontact',
            name='whats_reg_checked_data',
            field=models.DateField(default=None),
        ),
    ]
