# Generated by Django 4.2 on 2023-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_alter_senderemail_is_check_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderphonenumber',
            name='contact',
            field=models.CharField(max_length=50, null=True, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='senderphonenumber',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
