# Generated by Django 4.2 on 2023-07-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_recipientcontact_is_phone_whatsapp_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientcontact',
            name='whats_reg_checked_data',
            field=models.DateField(default=None, null=True),
        ),
    ]
