# Generated by Django 4.2 on 2023-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_contactimportfiles_row_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactimportfiles',
            name='is_contains_headers',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
