# Generated by Django 4.2 on 2023-07-17 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_alter_recipientcontact_is_phone_whatsapp_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контакт')),
                ('login_date', models.DateField(default=None, null=True)),
                ('is_login', models.BooleanField(default=False, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Контакт')),
                ('password', models.CharField(max_length=50)),
                ('checked_data', models.DateField(default=None, null=True)),
                ('is_valid', models.BooleanField(default=False, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
