# Generated by Django 4.2 on 2023-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_senderphonenumber_senderemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientcontact',
            name='whats_reg_checked_data',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='senderphonenumber',
            name='login_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
