# Generated by Django 4.2 on 2023-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_contactimportfiles_is_contains_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactimportfiles',
            name='is_imported',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Import',
        ),
    ]
