# Generated by Django 4.2 on 2023-08-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0009_contactimportfiles_is_imported_delete_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactimportfiles',
            name='all_handled_lines',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contactimportfiles',
            name='fail_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contactimportfiles',
            name='partial_success_create_update_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contactimportfiles',
            name='success_create_update_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
