# Generated by Django 4.2 on 2023-08-30 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0011_alter_contactimportfiles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientcontact',
            name='is_phone_whatsapp_reg',
            field=models.BooleanField(default=None, null=True, verbose_name='Телефон проверен на наличие в WhatsApp'),
        ),
        migrations.AlterField(
            model_name='userlettertext',
            name='text',
            field=models.TextField(null=True, verbose_name='Tекст письма'),
        ),
        migrations.AlterField(
            model_name='usersenders',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='UserSendersContactStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_send', models.BooleanField(null=True)),
                ('comment', models.TextField(null=True, verbose_name='Комментарий')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.recipientcontact', verbose_name='Контакт')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.usersenders', verbose_name='Рассылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
