# Generated by Django 4.2 on 2023-08-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0013_alter_usersenders_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersenders',
            name='count_letter',
            field=models.PositiveIntegerField(null=True, verbose_name='Число отправленных сообщений'),
        ),
    ]
