# Generated by Django 4.2 on 2023-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0014_alter_usersenders_count_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_duration_sec', models.PositiveIntegerField(default=120, verbose_name='Длительность ожидания входа в WhatsApp')),
                ('sleep_time', models.PositiveIntegerField(default=10, verbose_name='Задержка между проверками сканирования qr')),
                ('timeout_before_mail_sec', models.PositiveIntegerField(default=3, verbose_name='Задержка между сообщениями')),
            ],
        ),
        migrations.AddField(
            model_name='senderphonenumber',
            name='last_login_request',
            field=models.TimeField(null=True),
        ),
    ]
