# Generated by Django 4.2 on 2023-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0015_admindata_senderphonenumber_last_login_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderphonenumber',
            name='last_login_request',
            field=models.DateTimeField(null=True),
        ),
    ]
