# Generated by Django 4.2 on 2023-09-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0018_alter_senderphonenumber_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='check_login_time_sec',
            field=models.PositiveIntegerField(default=120, verbose_name='Длительность возможности проверки входа при авторизации в WhatsApp, сек'),
        ),
        migrations.AddField(
            model_name='senderphonenumber',
            name='last_login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='login_duration_sec',
            field=models.PositiveIntegerField(default=120, verbose_name='Длительность ожидания входа в WhatsApp, сек'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='sleep_time',
            field=models.PositiveIntegerField(default=10, verbose_name='Задержка между проверками сканирования qr, сек'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='timeout_before_mail_sec',
            field=models.PositiveIntegerField(default=3, verbose_name='Задержка между сообщениями, сек'),
        ),
        migrations.AlterField(
            model_name='senderphonenumber',
            name='qr_code',
            field=models.ImageField(default=None, null=True, upload_to='C:\\Users\\s121917\\PycharmProjects\\email_sender\\sources/media/qr_codes'),
        ),
    ]
