# Generated by Django 4.2 on 2023-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0019_admindata_check_login_time_sec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderphonenumber',
            name='last_login_time',
        ),
        migrations.AlterField(
            model_name='senderphonenumber',
            name='login_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
