# Generated by Django 4.2 on 2023-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0020_remove_senderphonenumber_last_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderphonenumber',
            name='is_login_start',
            field=models.BooleanField(default=False),
        ),
    ]
