# Generated by Django 4.2 on 2023-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0021_senderphonenumber_is_login_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='repeat_check_attempt',
            field=models.PositiveIntegerField(default=3, verbose_name='Кол-во попыток при повторной проверка логина в whatsApp'),
        ),
    ]
