# Generated by Django 4.2 on 2023-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0023_alter_usersenders_text_alter_usersenders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersenders',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersenders',
            name='type',
            field=models.CharField(choices=[('wa', 'WhatsApp'), ('em', 'Email')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usersenders',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
