# Generated by Django 4.2 on 2023-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0024_usersenders_finish_date_usersenders_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersenders',
            name='account_error_msg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usersenders',
            name='is_account_validation_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersenders',
            name='is_error_with_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersenders',
            name='count_letter',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Число отправленных сообщений'),
        ),
    ]
