# Generated by Django 4.2 on 2023-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0025_usersenders_account_error_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderphonenumber',
            name='last_login_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senderphonenumber',
            name='qr_code',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='C:\\Users\\s121917\\PycharmProjects\\email_sender\\sources/media/qr_codes'),
        ),
    ]
