# Generated by Django 4.2 on 2023-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0028_remove_contactcheckstatistic_is_check_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderphonenumber',
            name='qr_code',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes/'),
        ),
    ]
