# Generated by Django 4.2 on 2023-09-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0029_alter_senderphonenumber_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderemail',
            name='login_error_msg',
            field=models.TextField(null=True),
        ),
    ]
