# Generated by Django 4.2 on 2023-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0030_senderemail_login_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderemail',
            name='checked_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='senderemail',
            name='is_check_pass',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='senderemail',
            name='login_error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senderemail',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='senderemail',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
    ]
