# Generated by Django 4.2 on 2023-04-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_contactgroup_recipientcontact_contact_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlettertext',
            name='letter_subject',
            field=models.CharField(default=1, max_length=100, verbose_name='Тема письма для клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlettertext',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Внутренние название письма'),
            preserve_default=False,
        ),
    ]
