# Generated by Django 4.2 on 2023-04-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_userlettertext_letter_subject_userlettertext_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
