# Generated by Django 4.1.7 on 2023-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_user_api_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientcontact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='recipientcontact',
            name='type',
        ),
        migrations.AddField(
            model_name='recipientcontact',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipientcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='recipientcontact',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recipientcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='recipientcontact',
            name='senders',
            field=models.ManyToManyField(blank=True, null=True, to='sender.usersenders'),
        ),
        migrations.AddField(
            model_name='recipientcontact',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usersenders',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipientcontact',
            name='contact_group',
        ),
        migrations.AddField(
            model_name='recipientcontact',
            name='contact_group',
            field=models.ManyToManyField(null=True, to='sender.contactgroup'),
        ),
    ]
